export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_LOADING = 'SET_LOADING';
export const SET_INGREDIENTS_FAIL = 'SET_INGREDIENTS_FAIL';
export const SET_INGREDIENTS_SUCCESS = 'SET_INGREDIENTS_SUCCESS';
export const UNSET_LOADING = 'UNSET_LOADING';
